version: '3.2'

services:
 
  covid19-remote-work-api:
    image: bb.com.br/covid19-remote-certificate-issuer
    build: .
    restart: always
    network_mode: bridge
    ports:
      - 8000:8000
    environment: 
      - BASE_URL=http://localhost:8000
